### ISSUE TITLE
Rich text editing

### ISSUE THREAD

**Issue by adamdejl** [ic-drp02/drp-client-mobile#12]

**Comment by hasali19** [comment]
I've been researching this for the past hour and I don't think it's going to be possible to implement in the mobile app unless we eject from expo.

It should be relatively trivial to implement in the web app though.

**Comment by hasali19** [comment]
The above refers to editing of course, rendering is trivial. See #14.

**Comment by hasali19** [comment]
I think a simple version of this (think WhatsApp style) might be doable.
